## Microbial Metabolites Associated in Stool and Left Ventricle of Heart Failure Patients Revealed by Meta-Analysis

#### Emily F. Wissel, Hsin-Yuan Chien, Ke-Hsuan Wei, Yi-Chan Lee, Kiramat Ullah, Patrick C.H. Hsieh 
Institute of Biomedical Sciences, Academia Sinica, Taipei, 115, Taiwan


#### Abstract
Heart Failure (HF) is a leading cause of death, impacting approximately 64 million people globally. While overall incidence of HF is relatively stable across countries, the overall number of HF patients is increasing due to aging populations. Many articles have been published on the role of the microbiome in recovery after HF, however, this research from humans has not been systematically combined for analysis. The aim of this meta-analysis is to bridge this gap by analyzing previously published research on human heart failure patients with untargeted metabolomics to understand whether microbially-mediated metabolites are important for heart failure development or recovery.

*Methods*: A systematic survey of the literature identified 708 articles discussing HF, the microbiome, and metabolomics. Of these, 82 were primary studies of heart failure patients, 61 involved human adults, 23 included an untargeted metabolomics measure, and 3 studies had data that was usable and publicly accessible. These studies include a GCMS study from the stool of HF patients and controls, NMR of saliva and exhaled breath condensate from HF and control, and LCMS from left ventricle of HF patients undergoing transplantation therapy and unused donor hearts. 

*Results*: Significant differences were observed from PCA between HF and control samples for stool and left ventricle, but not saliva or EBC samples. OPLS-DA was conducted for stool and ventricle samples, and further revealed significant group differences as well as the direction which metabolites contribute to variance. Univariate testing with FDR correction of p values revealed 8 significant microbially relevant metabolites (p < 0.005 after correction), most notably asparagine from left ventricle and 2-methylbutyryl carnitine from stool. 

*Conclusion*: Overall, this meta-analysis found, though there is much discussion of the role of the microbiome in health outcomes in heart failure, limited research has been conducted in human populations. Overall, some microbial co-metabolites from both stool and heart were significantly associated with HF. Future work should dig deeper into the mechanisms behind these associations.

For analysis script and results, [please proceed to this link](https://ewissel.github.io/HF_Metabolomics_MetaAnalysis/for-publication-meta-analysis.html).

R Working environment is too big for github and can be found on FigShare here: 10.6084/m9.figshare.27014218 

For the publication, please proceed to this link: <put-here>


